In [1]:
import pandas as pd

# Process EPC non-domestic

In [2]:
sample_nd = pd.read_csv("data/epc-nondomestic.csv", nrows=1000)
sample_nd.head()

,certificate_number,address1,address2,address3,posttown,postcode,address,constituency,constituency_label,local_authority,...,building_emissions,aircon_present,aircon_kw_rating,estimated_aircon_kw_rating,ac_inspection_commissioned,building_environment,report_type,primary_energy_value,uprn,uprn_source
0,0000-7404-5801-3694-5935,Rowan House,Hill End Lane,NaN,ST ALBANS,AL4 0RA,"Rowan House, Hill End Lane",E14001507,St Albans,E07000240,...,35.76,No,NaN,NaN,4,Heating and Natural Ventilation,3,221.99,1.000107e+10,Energy Assessor
1,0000-9278-0696-8196-1282,42 George Street,Great Harwood,NaN,BLACKBURN,BB6 7JF,"42 George Street, Great Harwood",E14001299,Hyndburn,E07000120,...,159.05,No,NaN,NaN,4,Heating and Natural Ventilation,3,884.97,1.000104e+11,Energy Assessor
2,0001-2150-4009-1081-1260,251-253 London Road East,Batheaston,NaN,Bath,BA1 7RL,"251-253 London Road East, Batheaston",E14001080,Bath,E06000022,...,69.44,No,NaN,NaN,4,Heating and Natural Ventilation,3,401.12,1.001212e+11,Energy Assessor
3,0001-2823-0043-0321-7174,BLACK HORSE,COVENTRY ROAD,MARTON,CV23 9RH,CV23 9RH,"BLACK HORSE, COVENTRY ROAD, MARTON",E14001309,Kenilworth and Southam,E07000220,...,82.62,No,NaN,NaN,4,Heating and Natural Ventilation,3,614.19,1.001052e+10,Address Matched
4,0001-6857-5728-6832-3157,143 WATER STREET,RADCLIFFE,NaN,RADCLIFFE,M26 3BJ,"143 WATER STREET, RADCLIFFE",E14001145,Bury South,E08000002,...,33.44,No,NaN,NaN,4,Heating and Natural Ventilation,3,193.75,1.000124e+11,Energy Assessor

In [3]:
cols_nd = ["asset_rating_band", 
           "property_type", 
           "lodgement_date",
           "main_heating_fuel",
           "other_fuel_desc",
           "special_energy_uses",
           "renewable_sources",
           "floor_area",
           "asset_rating",
           "inspection_date",
           "standard_emissions",
           "target_emissions",
           "typical_emissions",
           "building_emissions",
           "aircon_present",
           "lodgement_datetime",
           "primary_energy_value",
           "building_level",
           "ac_inspection_commissioned",
           "building_environment",
           "uprn"
           ]
df_nd = pd.read_csv("data/epc-nondomestic.csv", usecols=cols_nd)
df_nd.head()

,asset_rating,asset_rating_band,property_type,inspection_date,lodgement_date,lodgement_datetime,building_level,main_heating_fuel,other_fuel_desc,special_energy_uses,...,floor_area,standard_emissions,target_emissions,typical_emissions,building_emissions,aircon_present,ac_inspection_commissioned,building_environment,primary_energy_value,uprn
0,77,D,Offices and Workshop Businesses,2023-09-19,2023-09-25,2023-09-25 14:34:24,3,Natural Gas,NaN,NaN,...,45,23.15,9.44,37.84,35.76,No,4,Heating and Natural Ventilation,221.99,1.000107e+10
1,58,C,Hotels,2022-09-12,2022-09-16,2022-09-20 19:17:12,3,Natural Gas,NaN,NaN,...,133,136.78,88.90,356.50,159.05,No,4,Heating and Natural Ventilation,884.97,1.000104e+11
2,81,D,B1 Offices and Workshop businesses,2022-03-05,2022-03-05,2022-03-05 07:43:45,3,Natural Gas,NaN,NaN,...,369,42.82,18.01,52.78,69.44,No,4,Heating and Natural Ventilation,401.12,1.001212e+11
3,72,C,Restaurants and Cafes/Drinking Establishments/...,2023-12-12,2024-01-31,2024-01-31 16:42:08,3,Natural Gas,NaN,NaN,...,355,57.27,27.34,109.63,82.62,No,4,Heating and Natural Ventilation,614.19,1.001052e+10
4,66,C,A1/A2 Retail and Financial/Professional services,2020-10-05,2020-10-07,2020-10-07 19:08:45,3,Natural Gas,NaN,NaN,...,579,25.14,13.81,40.46,33.44,No,4,Heating and Natural Ventilation,193.75,1.000124e+11

In [4]:
df_nd.columns = df_nd.columns.str.replace("_", " ")
df_nd.columns = df_nd.columns.str.title()
df_nd.columns = df_nd.columns.str.replace(" ", "")
df_nd.head()

,AssetRating,AssetRatingBand,PropertyType,InspectionDate,LodgementDate,LodgementDatetime,BuildingLevel,MainHeatingFuel,OtherFuelDesc,SpecialEnergyUses,...,FloorArea,StandardEmissions,TargetEmissions,TypicalEmissions,BuildingEmissions,AirconPresent,AcInspectionCommissioned,BuildingEnvironment,PrimaryEnergyValue,Uprn
0,77,D,Offices and Workshop Businesses,2023-09-19,2023-09-25,2023-09-25 14:34:24,3,Natural Gas,NaN,NaN,...,45,23.15,9.44,37.84,35.76,No,4,Heating and Natural Ventilation,221.99,1.000107e+10
1,58,C,Hotels,2022-09-12,2022-09-16,2022-09-20 19:17:12,3,Natural Gas,NaN,NaN,...,133,136.78,88.90,356.50,159.05,No,4,Heating and Natural Ventilation,884.97,1.000104e+11
2,81,D,B1 Offices and Workshop businesses,2022-03-05,2022-03-05,2022-03-05 07:43:45,3,Natural Gas,NaN,NaN,...,369,42.82,18.01,52.78,69.44,No,4,Heating and Natural Ventilation,401.12,1.001212e+11
3,72,C,Restaurants and Cafes/Drinking Establishments/...,2023-12-12,2024-01-31,2024-01-31 16:42:08,3,Natural Gas,NaN,NaN,...,355,57.27,27.34,109.63,82.62,No,4,Heating and Natural Ventilation,614.19,1.001052e+10
4,66,C,A1/A2 Retail and Financial/Professional services,2020-10-05,2020-10-07,2020-10-07 19:08:45,3,Natural Gas,NaN,NaN,...,579,25.14,13.81,40.46,33.44,No,4,Heating and Natural Ventilation,193.75,1.000124e+11

# Process EPC domestic

In [ ]:
sample_domestic = pd.read_csv("data/epc-domestic.csv", nrows=1000)
sample_domestic.head()

In [ ]:
sample_domestic.dtypes

In [ ]:
sample_domestic.describe()